### ISSUE TITLE
[Feature] Disable multiple bin packing

### ISSUE THREAD

**Issue by amitrajitbose** [olragon/binpackingjs#10]
Really nice work on implementing this. I am trying to disable multiple bin packing, rather I want to use a single bin for packing all the items.
Is there any undocumented way for the library to support single bin packing for 3D packing instead of multiple bin packing? @olragon 
If not, do you have any idea how to tweak this setting?

**Comment by olragon** [comment]
@amitrajitbose
- implement custom [heuristics](https://github.com/olragon/binpackingjs/blob/master/src/2D/heuristics/BestAreaFit.js) and feed it to [`Bin`](https://github.com/olragon/binpackingjs/blob/master/src/2D/Bin.js#L12)
- the simplest and dumbest way is brute force, try to pack all items with single bin then compare

**Comment by amitrajitbose** [comment]
@olragon 
What about 3D packing? How do we add a custom heuristic for it. The [constructor](https://github.com/olragon/binpackingjs/blob/0b71dd890a7606619404e614f5386dd32312389e/src/3D/Bin.js#L11) does not take any such argument.

**Comment by olragon** [comment]
@amitrajitbose 
You can subclass [`Packer`](https://github.com/olragon/binpackingjs/blob/master/src/3D/Packer.js#L10)
