### ISSUE TITLE
Determine smallest possible size bin to use

### ISSUE THREAD

**Issue by brandonros** [olragon/binpackingjs#6]
I have 11,875 possible bin combinations (from 6x6x2" to 30x20x20") and a list of items that need to be shipped. Is it possible to figure out the smallest (most effective shipping cost wise) bin to pack items in?

**Comment by olragon** [comment]
"most effective shipping cost wise" depend on what you are saving cost or space.
- if you are saving cost, which bin is the most effective cost? a small number of large bin or a large number of small bin?
- if you are saving space, the small bin should be referred

**Comment by seanyu4296** [comment]
@brandonros where you able to find a good way to find the most cost effective bin combination?
